[tool.poetry]
name = "aiopywttr"
version = "1.0.2"
description = "Asynchronous wrapper for wttr.in"
authors = ["monosans <hsyqixco@protonmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/monosans/aiopywttr"
keywords = ["forecast", "weather"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.7"
pywttr-models = "^0.1"
aiohttp = "^3.8"

[tool.poetry.dev-dependencies]
black = "^22.3"
isort = "^5.10"
mypy = "^0.960"
pre-commit = "^2.19"
pytest = "^7.1"
pytest-cov = "^3.0"
pytest-asyncio = "^0.18"

[tool.black]
line-length = 79
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 79

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "--strict-markers --strict-config --cov --asyncio-mode=auto"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
