[tool.poetry]
name = "aiopywttr"
version = "1.0.0"
description = "Asynchronous wrapper for wttr.in"
authors = ["monosans <hsyqixco@protonmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/monosans/aiopywttr"
keywords = [
  "forecast",
  "weather",
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.7"
pywttr-models = "^0.1.1"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]
black = "^22.1"
isort = "^5.10.1"
mypy = "^0.931"
pre-commit = "^2.17.0"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.18.0"

[tool.black]
line-length = 79
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 79

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "--strict-markers --strict-config --cov --asyncio-mode=auto"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
